### ISSUE TITLE
Local development

### ISSUE THREAD

**Issue by kaihendry** [aquasecurity/lmdrouter#1]
This [welcome abstraction](https://dabase.com/blog/2020/sam-sucks/) doesn't facilitate local development with https://github.com/codegangsta/gin for example, does it?

**Comment by ido50** [comment]
I've actually been thinking about some form of abstraction like this, exactly for local development purposes. Currently we have a local server that exposes the same API, but some code has to be different because of this limitation.

So an abstraction like you're suggesting should make it into the library very soon, I'll keep you posted.

**Comment by kaihendry** [comment]
I've found a workflow with Apex Up. If you don't want to use Apex Up, @tjholowaychuck published https://github.com/apex/gateway which is the basis of my work this Sunday https://github.com/kaihendry/aws-sam-gateway-example

**Comment by ido50** [comment]
A solution for this has now been provided in v0.4.4. A `*router` object now implements `net/http.Handler`, so it can easily be used locally.
